### ISSUE TITLE
Can I install this on my Macbook Pro with NVIDIA GTX 650M

### ISSUE THREAD

**Issue by xmurobi** [chris1111/Fix-Old-NVIDIA-macOS-Mojave#3]
I had check the install info. but can't see the GTX 650M support on the list. Can I install this on my macbook pro to react the CUDA on Mojave?

**Comment by chris1111** [comment]
> I had check the install info. but can't see the GTX 650M support on the list. Can I install this on my macbook pro to react the CUDA on Mojave?

No absolutely not!

**Comment by xmurobi** [comment]
@chris1111 Could you help to patch GeForceWeb.kext?
